# Generated by Django 5.0.4 on 2024-11-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_product'),
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.register')),
            ],
        ),
    ]
