# Generated by Django 5.0.4 on 2024-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cdesc', models.CharField(max_length=100)),
                ('cimage', models.ImageField(upload_to='cimages')),
            ],
        ),
    ]
