# Generated by Django 5.0.4 on 2024-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pcat', models.CharField(max_length=100)),
                ('pprice', models.IntegerField()),
                ('pstock', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='pimages')),
            ],
        ),
    ]
